# Kernel and Rank:

In [6]:
import numpy as np
import sympy

In [7]:
B = np.matrix('1 2 3; 4 5 6; 7 8 9; 10 11 12')
print (B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
B = sympy.Matrix(B)
e_B = B.echelon_form()
e_B

Matrix([
[1,  2,  3],
[0, -3, -6],
[0,  0,  0],
[0,  0,  0]])

In [9]:
re_B = B.rref()[0]
re_B

Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0],
[0, 0,  0]])

In [10]:
n_B = B.nullspace()
n_B

[Matrix([
 [ 1],
 [-2],
 [ 1]])]

## What we can infer from this:

- number of Pivots = 2
Therefore the rank = 2

